### ISSUE TITLE
Black Ops 3 Support?

### ISSUE THREAD

**Issue by etkramer** [sheilan102/husky_modified#10]
AFAIK it's running on an older engine version than Infinite Warfare. Is there a technical reason why it's unsupported, or have you just not had a chance to test it?

**Comment by o-Astral-o** [comment]
Hi mate. i know this is late but as far as i'm aware Scobalula (Husky dev) said he wont add support for BO3 in order to prevent people ripping peoples custom maps, However as this is a fork of the original i suppose it would be up to the developer of C2M to add support in the future although i personally doubt it, Sorry to have to let you down my man.

**Comment by Airyzz** [comment]
Black Ops 3 is supported in C2M v2.0 https://sheilan102.github.io/C2M/
